import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));let failed=false;const pass=m=>console.log('PASS '+m),fail=m=>{failed=true;console.error('FAIL '+m)},sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const baselineDoc=JSON.parse(read('scripts/NX_COLLAB_1_R2_BASELINE_SHA256.json')),baseline=baselineDoc.files||{};
const changed=new Set(['public/admin/css/admin.css','public/admin/js/core/design-system.js','public/admin/js/core/i18n.js','public/admin/js/modules/client-project-support.js','public/admin/js/modules/client-projects.js','public/css/nexora-foundation.css','public/css/project-portal.css','public/js/project-portal.js','public/project-portal.html','src/api-router.js','src/core/crypto.js','src/modules/operations/client-project-execution.js','src/modules/operations/client-project-support.js','src/modules/operations/client-projects.js','src/worker.js','wrangler.jsonc']);
for(const [rel,h] of Object.entries(baseline)){if(changed.has(rel))continue;const p=path.join(root,rel);if(!fs.existsSync(p)||sha(p)!==h)fail('R2 baseline changed outside approved surface: '+rel)}if(!failed)pass('NX-OPS-4 R2 baseline protected outside approved surface');
const addedExpected=new Set(['NX_COLLAB_1_FINAL_CHECK.md','NX_COLLAB_1_README.md','docs/NX_COLLAB_1_REALTIME_FILES_FOUNDATION.md','migrations/0010_client_project_collaboration.sql','scripts/APPLY_NX_COLLAB_1.ps1','scripts/NX_COLLAB_1_CHECK.mjs','scripts/NX_COLLAB_1_FULL_SCHEMA_REGRESSION.mjs','scripts/NX_COLLAB_1_R2_BASELINE_SHA256.json','scripts/NX_COLLAB_1_RELEASE_MANIFEST.json','scripts/NX_DATA_5_CHECK.mjs','scripts/RUN_NX_COLLAB_1_RELEASE.ps1','src/cloudflare-worker.js','src/core/project-realtime.js','src/modules/operations/client-project-files.js','tests/nx-collab-1/ui-contract.mjs','tests/nx-collab-1/worker-integration.mjs','tests/nx-data-5/schema-proof.py']);
const inventory=[];function inv(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.wrangler'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())inv(p);else inventory.push(path.relative(root,p).replaceAll('\\','/'))}}inv(root);const addedActual=new Set(inventory.filter(x=>!Object.hasOwn(baseline,x)));const missing=[...addedExpected].filter(x=>!addedActual.has(x)),extra=[...addedActual].filter(x=>!addedExpected.has(x));if(missing.length||extra.length)fail('added-file inventory mismatch missing=['+missing+'] extra=['+extra+']');else pass('NX-COLLAB-1 added-file inventory exact ('+addedActual.size+')');
const migrations=fs.readdirSync(path.join(root,'migrations')).filter(x=>/^\d{4}_.+\.sql$/.test(x)).sort();const expected=['0001_schema.sql','0002_seed.sql','0003_inquiry_locale.sql','0004_clients_core.sql','0005_clients_hardening.sql','0006_clients_code_alignment.sql','0007_client_projects.sql','0008_client_project_execution.sql','0009_client_project_portal_support.sql','0010_client_project_collaboration.sql'];migrations.join('|')===expected.join('|')?pass('migration inventory exact 0001..0010'):fail('migration inventory mismatch: '+migrations.join(','));
const router=read('src/api-router.js');/method\s*===\s*['"]DELETE['"]/.test(router)?fail('HTTP DELETE route introduced'):pass('no HTTP DELETE route introduced');
const routeCount=(router.match(/if\(method===/g)||[]).length;routeCount===89?pass('API route inventory exact (89 route guards)'):fail('API route inventory changed: '+routeCount);
const wr=read('wrangler.jsonc');for(const s of ['PROJECT_REALTIME','ProjectRealtimeRoom','PROJECT_FILES','nexora-project-files'])wr.includes(s)?pass('Cloudflare contract '+s):fail('missing Cloudflare contract '+s);
const wrCfg=JSON.parse(wr);const cfEntry=read('src/cloudflare-worker.js'),nodeEntry=read('src/worker.js');
wrCfg.main==='./src/cloudflare-worker.js'?pass('Cloudflare deployment entrypoint is src/cloudflare-worker.js'):fail('Cloudflare deployment entrypoint mismatch: '+wrCfg.main);
/export\s+class\s+ProjectRealtimeRoom\s+extends\s+DurableObject/.test(cfEntry)?pass('Cloudflare entrypoint exports ProjectRealtimeRoom'):fail('ProjectRealtimeRoom is not exported from Cloudflare entrypoint');
/export\s+default\s+worker/.test(cfEntry)?pass('Cloudflare entrypoint preserves default Worker handler'):fail('Cloudflare entrypoint does not export default Worker handler');
!nodeEntry.includes('cloudflare:workers')?pass('Node test entrypoint remains Cloudflare-import free'):fail('Node test entrypoint imports cloudflare:workers');
for(const rel of ['scripts/APPLY_NX_COLLAB_1.ps1','scripts/RUN_NX_COLLAB_1_RELEASE.ps1']){const b=fs.readFileSync(path.join(root,rel));if([...b].some(x=>x>127))fail('PowerShell script is not ASCII-safe: '+rel)}if(!failed)pass('release-critical PowerShell scripts are ASCII-safe');
const applyPs=read('scripts/APPLY_NX_COLLAB_1.ps1');for(const token of ["$D1ReadMaxAttempts = 4",'function Test-TransientD1ReadFailure',"fetch failed",'WARN transient D1 read failure']){if(!applyPs.includes(token))fail('missing resilient D1 read retry contract: '+token)}if(!failed)pass('read-only D1 count retry/backoff contract present');
for(const rel of ['scripts/NX_DATA_5_CHECK.mjs','scripts/NX_COLLAB_1_FULL_SCHEMA_REGRESSION.mjs','tests/nx-collab-1/worker-integration.mjs','tests/nx-collab-1/ui-contract.mjs']){const r=spawnSync(process.execPath,[path.join(root,rel)],{cwd:root,encoding:'utf8',env:{...process.env,NODE_NO_WARNINGS:'1'}});process.stdout.write(r.stdout||'');process.stderr.write(r.stderr||'');if(r.status!==0)fail('gate '+rel);else pass(rel)}
for(const rel of ['tests/nx-core-2/worker-parity.mjs','tests/nx-ops-1/existing-admin-compat.mjs']){const r=spawnSync(process.execPath,[path.join(root,rel)],{cwd:root,encoding:'utf8',env:{...process.env,NODE_NO_WARNINGS:'1'}});process.stdout.write(r.stdout||'');process.stderr.write(r.stderr||'');if(r.status!==0)fail('regression '+rel);else pass('regression '+rel)}
const js=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.wrangler'].includes(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(/\.(?:js|mjs)$/.test(e.name))js.push(p)}}walk(path.join(root,'src'));walk(path.join(root,'public'));for(const p of js){const r=spawnSync(process.execPath,['--check',p],{encoding:'utf8'});if(r.status!==0){fail('JS syntax '+path.relative(root,p));break}}if(!failed)pass('runtime JavaScript syntax');
const html=[];walkHtml(path.join(root,'public'));function walkHtml(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walkHtml(p);else if(e.name.endsWith('.html'))html.push(p)}}for(const p of html){const ids=[...fs.readFileSync(p,'utf8').matchAll(/\bid=["']([^"']+)/g)].map(m=>m[1]),set=new Set();for(const id of ids){if(set.has(id))fail('duplicate HTML id '+path.relative(root,p)+'#'+id);set.add(id)}}if(!failed)pass('HTML duplicate IDs');
console.log('\nNX-COLLAB-1 CHECK: '+(failed?'FAIL':'PASS'));process.exit(failed?1:0);
