import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root=fileURLToPath(new URL('../',import.meta.url));
const candidates=[process.env.CHROME_PATH,process.platform==='win32'&&process.env.PROGRAMFILES?path.join(process.env.PROGRAMFILES,'Google','Chrome','Application','chrome.exe'):null,process.platform==='win32'&&process.env['PROGRAMFILES(X86)']?path.join(process.env['PROGRAMFILES(X86)'],'Google','Chrome','Application','chrome.exe'):null,process.platform==='win32'&&process.env.LOCALAPPDATA?path.join(process.env.LOCALAPPDATA,'Google','Chrome','Application','chrome.exe'):null,process.platform==='win32'&&process.env.PROGRAMFILES?path.join(process.env.PROGRAMFILES,'Microsoft','Edge','Application','msedge.exe'):null,'/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'].filter(Boolean);
const browserPath=candidates.find(p=>fs.existsSync(p));
if(!browserPath){console.error('FAIL R4.2 browser gate: Chrome/Edge/Chromium not found. Set CHROME_PATH.');process.exit(1)}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function freePort(){return await new Promise((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const {port}=s.address();s.close(()=>resolve(port))})})}
async function waitJson(url,timeout=12000){const end=Date.now()+timeout;let last;while(Date.now()<end){try{const r=await fetch(url);if(r.ok)return await r.json()}catch(e){last=e}await sleep(120)}throw new Error(`Chrome DevTools did not become ready: ${last?.message||'timeout'}`)}
function cdp(wsUrl){const ws=new WebSocket(wsUrl);let id=0;const pending=new Map();const ready=new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',()=>reject(new Error('CDP websocket error')),{once:true})});ws.addEventListener('message',ev=>{const m=JSON.parse(ev.data);if(m.id&&pending.has(m.id)){const {resolve,reject}=pending.get(m.id);pending.delete(m.id);m.error?reject(new Error(m.error.message)):resolve(m.result)}});const send=async(method,params={})=>{await ready;const n=++id;return await new Promise((resolve,reject)=>{pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}))})};return {send,close:()=>ws.close(),ready}}
const cases=[[1728,900],[1440,900],[1366,768],[1280,720],[1024,768],[768,1024],[390,844],[360,800]];
const port=await freePort();const profile=fs.mkdtempSync(path.join(os.tmpdir(),'nexora-r4-2-browser-'));
const args=[`--remote-debugging-port=${port}`,'--remote-debugging-address=127.0.0.1','--headless=new','--disable-gpu','--disable-extensions','--disable-background-networking','--disable-component-update','--no-first-run','--no-default-browser-check',`--user-data-dir=${profile}`,'about:blank'];if(process.platform!=='win32')args.unshift('--no-sandbox');
console.log('R4.2 browser engine: '+browserPath);const child=spawn(browserPath,args,{stdio:['ignore','ignore','ignore']});let failed=false;
try{
 await waitJson(`http://127.0.0.1:${port}/json/version`);const target=await fetch(`http://127.0.0.1:${port}/json/new?about:blank`,{method:'PUT'}).then(r=>r.json());const client=cdp(target.webSocketDebuggerUrl);await client.ready;await client.send('Page.enable');
 const foundation=fs.readFileSync(path.join(root,'public','css','nexora-foundation.css'),'utf8');const adminCss=fs.readFileSync(path.join(root,'public','admin','css','admin.css'),'utf8');let html=fs.readFileSync(path.join(root,'tests','nx-collab-1-r4-2-support-density-visual.html'),'utf8');html=html.replace('<link rel="stylesheet" href="../../public/css/nexora-foundation.css">',`<style>${foundation}</style>`).replace('<link rel="stylesheet" href="../../public/admin/css/admin.css">',`<style>${adminCss}</style>`);
 for(const [w,h] of cases){
  await client.send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:false});const tree=await client.send('Page.getFrameTree');await client.send('Page.setDocumentContent',{frameId:tree.frameTree.frame.id,html});await sleep(120);
  const result=await client.send('Runtime.evaluate',{expression:`(()=>{const f=[];const E=s=>document.querySelector(s);const R=s=>E(s)?.getBoundingClientRect()||null;const hero=R('.project-command-hero'),nav=R('.project-workspace-nav'),content=R('.project-workspace-content'),thread=R('.admin-ticket-thread'),composer=R('.admin-ticket-composer'),sidebar=R('.admin-ticket-sidebar'),detail=R('.admin-ticket-detail');if(document.documentElement.scrollWidth>document.documentElement.clientWidth+1)f.push('horizontal overflow');if(document.documentElement.scrollHeight>document.documentElement.clientHeight+1)f.push('page vertical overflow');if(!hero||!nav||!content||!thread||!composer||!sidebar||!detail)f.push('density DOM missing');if(composer&&detail&&(composer.left<detail.left-1||composer.right>detail.right+1))f.push('composer horizontal overflow');if(innerWidth>=1024){if(hero&&hero.height>122)f.push('hero too tall '+Math.round(hero.height));if(nav&&nav.height>52)f.push('nav too tall '+Math.round(nav.height));if(content&&content.top>236)f.push('workspace starts too low '+Math.round(content.top));if(composer&&composer.height>96)f.push('composer too tall '+Math.round(composer.height));if(innerHeight<=768&&thread&&thread.height<235)f.push('thread height too small '+Math.round(thread.height));if(sidebar&&detail){const total=sidebar.width+detail.width;if(total>0){const ratio=sidebar.width/total;if(ratio<.29||ratio>.39)f.push('ticket density ratio '+ratio.toFixed(2));}}}if(innerWidth<=430){if(hero&&hero.height>92)f.push('mobile hero too tall '+Math.round(hero.height));if(nav&&nav.height>48)f.push('mobile nav too tall '+Math.round(nav.height));if(thread&&thread.height<90)f.push('mobile thread too small '+Math.round(thread.height));}return {f,hero:hero?.height||0,nav:nav?.height||0,contentTop:content?.top||0,thread:thread?.height||0,composer:composer?.height||0}})()`,returnByValue:true});
  const v=result.result?.value;if(v?.f?.length){failed=true;console.error(`FAIL R4.2 browser admin/density ${w}x${h}: ${v.f.join(' | ')}`)}else console.log(`PASS R4.2 browser admin/density ${w}x${h} hero=${Math.round(v.hero)} nav=${Math.round(v.nav)} contentTop=${Math.round(v.contentTop)} thread=${Math.round(v.thread)} composer=${Math.round(v.composer)}`);
 }
 client.close();
}catch(e){failed=true;console.error('FAIL R4.2 browser gate: '+e.message)}finally{child.kill('SIGTERM');await sleep(120);if(!child.killed)child.kill('SIGKILL');try{fs.rmSync(profile,{recursive:true,force:true})}catch{}}
console.log(`NX_COLLAB_1_UI_R4_2_BROWSER_GATE_${failed?'FAIL':'PASS'}`);process.exit(failed?1:0);
